$ErrorActionPreference="Continue"
$dst="D:\AppData_Migrate"; $u="C:\Users\xuyif"; $fso=New-Object -ComObject Scripting.FileSystemObject
New-Item -ItemType Directory -Path $dst -Force | Out-Null
function M($s,$n){$d="$dst\$n"; if(!(Test-Path $s)){Write"  SKIP $n";return}; $i=Get-Item $s -Force -EA SilentlyContinue; if($i -and ($i.Attributes -band 66)){Write"  SKIP-LINK $n";return}; try{$sz=[math]::Round(($fso.GetFolder($s).Size)/1GB,2);Write"  $n : ${sz}GB"}catch{}; robocopy "$s" "$d" /E /MOVE /R:1 /W:1 /NFL /NDL /NJH | Out-Null; if(Test-Path $s){Get-ChildItem $s -Recurse -Force -EA S | Remove-Item -Recurse -Force -EA S; Remove-Item $s -Recurse -Force -EA S}; try{New-Item -ItemType Junction -Path $s -Target $d -Force -ErrorAction Stop | Out-Null;Write"  OK $n"}catch{Write"  PARTIAL $n"}}
Write "===== STEP 4 ====="
M "$u\AppData\Roaming\LarkShell" "LarkShell"
M "$u\AppData\Roaming\Python" "Python_Roaming"
M "$u\AppData\Roaming\Code" "VSCode"
M "$u\AppData\Roaming\kingsoft" "WPS_kingsoft"
Write "`n===== STEP 5 ====="
M "$u\AppData\Roaming\Qoder" "Qoder"
M "$u\AppData\Roaming\Tencent" "Tencent"
M "$u\AppData\Local\npm-cache" "npm-cache_Local"
M "$u\AppData\Roaming\Lingma" "Lingma"
M "$u\AppData\Local\ms-playwright" "ms-playwright"
M "$u\AppData\Local\stm32cube" "stm32cube"
M "$u\AppData\Local\ESRI" "ESRI"
M "$u\AppData\Roaming\npm" "npm_Roaming"
M "$u\AppData\Roaming\Figma" "Figma"
M "$u\AppData\Roaming\Shandianshuo" "Shandianshuo"
M "$u\AppData\Local\nvm" "nvm"
M "$u\AppData\Local\Everything" "Everything"
M "$u\AppData\Local\Google" "Google"
M "$u\AppData\Local\JetBrains" "JetBrains"
M "$u\AppData\Local\AnthropicClaude" "AnthropicClaude"
Write "`n===== ALL DONE ====="
